# Dockerfile de exemplo para a aplicação
FROM python:3.11-slim
WORKDIR /app
COPY . /app
# Instale dependências adicionais conforme necessário
# RUN pip install -r requirements.txt
CMD ["python", "app.py"]
